apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: by1ep4q4q-go
  janus-idp.io/tekton: by1ep4q4q-go
  backstage.io/kubernetes-id: by1ep4q4q-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: by1ep4q4q-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
