apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: by1ep4q4q-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: by1ep4q4q-go 
  name: by1ep4q4q-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: by1ep4q4q-go 
